### ISSUE TITLE
Back links from bibliography to citation across documents

### ISSUE THREAD

**Issue by uellue** [mcmtroffaes/sphinxcontrib-bibtex#194]
Back links from the bibliography to the citation location work if the citation is in the same document. If a source is cited from another document, it is included in the bibliography, but without a back link. It would be great to have a back link here, too!

Is this a missing feature, bug, or perhaps a configuration issue on our side?

Refs https://github.com/LiberTEM/LiberTEM/issues/512

**Comment by mcmtroffaes** [comment]
Thanks for reporting, and sorry for the late reply! I think this might be a missing feature in sphinx, but I'm not entirely sure. I'll need to run some tests to see what's up.

**Comment by mcmtroffaes** [comment]
Apologies for the late reply here. I've finally had some time to look into this in more detail, and yes, it seems Sphinx/docutils does not add backlinks for citation nodes across documents. You can test this yourself with regular native Sphinx/docutils citations. Since the extension currently relies on the native implementation of those nodes, it won't generate those backlinks either. I suggest to check with upstream Sphinx if they are interested in adding this as a feature, since it would benefit not just this bibtex extension.

**Comment by uellue** [comment]
Ok , thank you for looking into it!
