### ISSUE TITLE
Produce 'citation_reference' nodes instead of plain 'reference' nodes

### ISSUE THREAD

**Issue by brechtm** [mcmtroffaes/sphinxcontrib-bibtex#275]
As a follow-up to #273, rendering a Sphinx project involving sphinxcontrib-bibtex using the _rinoh_ builder now is closer to producing the proper output (https://github.com/brechtm/rinohtype/issues/298#issuecomment-934543795). But it's not quite there yet. I want to ask you to consider making another change to sphinxcontrib-bibtex.

The extension produces a plain _reference_ node instead of a _citation_reference_ node [1]. Since you are outputting _citation_ nodes, it makes sense to also output _citation_reference_ nodes. This may be complicated by the presence (and order) of the Sphinx transforms. For example, it's possible that you need to output a _pending_xref_ node (equivalent to what a plain Sphinx citation produces) instead of a _citation_reference_ node.

@rappdw

[1] I would demonstrate this using output from Sphinx's pseudoxml builder, but the issue is not visible there due to the involvement of Sphinx transforms. Please see https://github.com/brechtm/rinohtype/issues/262#issuecomment-857629772 for some hints on what Sphinx is doing internally.

**Comment by brechtm** [comment]
Thanks for looking into this! I haven't had much time to spend on this, unfortunately.

I didn't dive deep into this yet (and therefore couldn't follow your analysis above fully), but I want to share the following:
- rinohtype [transforms](https://github.com/brechtm/rinohtype/blob/91fadbfff99d6184bac6a795934c9519c0f33ac1/src/rinoh/frontend/sphinx/transforms.py#L13) _pending_xref_ nodes back into _citation_reference_ nodes (~ the [LaTeX builder](https://github.com/sphinx-doc/sphinx/blob/9e1b4a8f1678e26670d34765e74edf3a3be3c62c/sphinx/builders/latex/transforms.py#L512))
  - more info here: https://github.com/brechtm/rinohtype/issues/262#issuecomment-857629772
- this transform uses the _reftarget_ attribute as the label for the citation reference
  - _reftarget_ does **not** include the brackets - rinohtype adds those by means of the [stylesheet](https://github.com/brechtm/rinohtype/blob/91fadbfff99d6184bac6a795934c9519c0f33ac1/src/rinoh/data/stylesheets/sphinx.rts#L625)

So, sphinxcontrib-bibtex could perhaps produce the same kind of _pending_xref_ node as Sphinx does for rST citation references, with:
- setting _reftarget_ to the citation reference label, and
- adding a "bibtex" class to the _pending_xref_ node so that it can be styled differently in rinohtype (leaving out the brackets)

I understand this will not work for the other builders. You mention a "special separate citation reference style". Could this be set independenly for each builder? I'm asking because people may want to generate both HTML and PDF from the same sources, without having to change this option when building both formats. Perhaps you could also check for the "rinoh" builder and output the difference _pending_xref_ just for it?

**Comment by mcmtroffaes** [comment]
> So, sphinxcontrib-bibtex could perhaps produce the same kind of _pending_xref_ node as Sphinx does for rST citation references

The reference content is only known after all documents have been processed, [in the env-updated stage](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/7b0e2acf5afd9a2f3f723938b150b3c29245574f/src/sphinxcontrib/bibtex/domain.py#L375-L417), and thus only after the pending_xref is created. For this reason, sphinxcontrib-bibtex produces its own pending_xrefs (in separate domains, ``cite`` for regular citations and ``footcite`` for footnote citations). It then produces the required reference nodes in the resolve stage. Post-resolve, this results in the same doctree structure as Sphinx does for regular citations (except for LaTeX because the LaTeX builder does not support regular reference nodes to citations).

> I understand this will not work for the other builders. You mention a "special separate citation reference style". Could this be set independenly for each builder?

The style is independent of the builder. But the rendering of the style can depend on the builder. For example, in all styles, currently, ``:cite:`` references are rendered into reference nodes (surrounded by other nodes for authors, brackets, ...) on all builders except latex, where it produces raw_latex nodes to create a custom hyperlink. A route could be pursued for rinotype if rinotype subjects itself to the same limitations as the LaTeX builder. I'm not sure what to generate though. Under the rinotype builder, what is the doctree structure in post-resolve stage for citation references, with custom content (i.e. content not necessarily equalling the label)?

**Comment by brechtm** [comment]
I finally found some time for a deeper dive into this problem. To my surprise, the fix is fairly simple because rinohtype will use the text specified for a citation_reference node (unlike the LaTeX builder?). All that is needed is adding the following lines to the body of the `SphinxReferencerText.render()` method:

```python
        elif info.builder.name == 'rinoh':
            key = f'%{info.todocname}#{info.citation_id}'
            children = super().render(backend)
            citnode = docutils.nodes.citation_reference(text=children[0],
                                                        refid=key,
                                                        reftitle=info.title)
            citnode.extend(children[1:])
            return [citnode]
```

One issue that remains is that both pybtex and rinohtype add brackets (https://github.com/brechtm/rinoh_error):
<img width="374" alt="image" src="https://user-images.githubusercontent.com/652887/160136527-fd4b6f4e-44eb-477f-8f99-16e62d2c7ed5.png">
The last reference here (CIT2002) is a plain docutils reference.

This can be solved by overriding the pre/suffix in rinohtype's stylesheet:
```ini
[citation marker]
label_prefix=''
label_suffix=''
```

But to be consistent with docutils, it would be better to have sphinxcontrib-bibtex omit the brackets when the rinoh builder is used.

P.S. I wasn't able to find out how to get "Nel87a"-style referencing working. Setting `bibtex_reference_style = 'author_year'` in _conf.py_ shows numbers in HTML output for the bibliography.

**Comment by mcmtroffaes** [comment]
Thanks for doing the research, it's good to know that it comes down to creating citation_reference nodes at the render stage. I think what suits best is a separate citation style that produces citation_reference nodes - the rinoh (and other) builders can then use that one single citation style. Overriding the bracket behaviour based on the builder is not on the table: since most styles render much more than just a citation_reference node and so some users might still want some bracket support, e.g. for multiple citations that are grouped together and so on.

I've been super busy but I promise I'll eventually get around to adding the style!

**Comment by mcmtroffaes** [comment]
>  I wasn't able to find out how to get "Nel87a"-style referencing working. Setting bibtex_reference_style = 'author_year' in conf.py shows numbers in HTML output for the bibliography.

For future reference: you're overriding the conf.py style in the rst document so the conf.py setting gets ignored. Just remove the ``:style:`` option from your rst and it should use the conf.py style again.

**Comment by brechtm** [comment]
> For future reference: you're overriding the conf.py style in the rst document so the conf.py setting gets ignored. Just remove the `:style:` option from your rst and it should use the conf.py style again.

👍 I didn't realize this.

> Also mind there's a difference between the citation label and the actual thing that appears in the reference link, unless one uses the label style. The new cit_ref_label style ensures these are always in sync as with standard sphinx citations.

I think this may be confusing me. When I render HTML with `bibtex_reference_style = 'author_year'`, the reference labels change(_1987_ or _Nelson, 1987_), but the labels in the bibliography remain the same (_Nel87_). That makes it confusing and harder to find the corresponding citation in the bibliography, doesn't it?

**Comment by mcmtroffaes** [comment]
> I think this may be confusing me. When I render HTML with `bibtex_reference_style = 'author_year'`, the reference labels change(_1987_ or _Nelson, 1987_), but the labels in the bibliography remain the same (_Nel87_). That makes it confusing and harder to find the corresponding citation in the bibliography, doesn't it?

Yes. It would be possible to have labels corresponding to the author and year, but that makes for very ugly formatting in the bibliography, unfortunately.

Just bear in mind that the reference style refers to how the citation reference is rendered (be it via labels, author/year, etc.), whilst the label style on the other hand refers to how the labels (as appearing in the bibliography) are rendered; the label style is declared as part of the bibliography style. These two styles are handled almost completely independently from each other. The only link is that some reference styles will use the labels (such as the "label" style), whilst others do not (such as the "author_year" style). The reference style handles a lot more, like how multiple citations are rendered together, where the author names appear, the shape of the brackets, etc.
