### ISSUE TITLE
handling of names with umlauts and tildes

### ISSUE THREAD

**Issue by jboynyc** [mcmtroffaes/sphinxcontrib-bibtex#319]
Thanks for this great package! I noticed one issue, I'm not sure whether this should be reported here or to [pybtex](https://bitbucket.org/pybtex-devs/pybtex/issues). 

As can be seen in two labels in [this bibliography](https://textnets.readthedocs.io/en/stable/bibliography.html), names of authors with an umlaut (in the case of Schütze in `MRSchutze08`) and a tilde (in the case of Boguñá in `SBogunaV09`) are not properly contracted to their first initial.

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Can you provide a minimal test project to reproduce the problem?

**Comment by jboynyc** [comment]
Sure, here it is: https://gist.github.com/jboynyc/882629d3851169da68d788c4b4c1015f

**Comment by mcmtroffaes** [comment]
Thanks, and apologies for taking such a long time. I've confirmed and debugged the issue with the test you provided. This is an upstream bug with the label abbreviation code in pybtex. I've posted an upstream issue along with a quick patch:

https://bitbucket.org/pybtex-devs/pybtex/issues/442/author-names-with-special-latex-characters

Thanks again for reporting! Hopefully this gets fixed in pybtex soon.
