### ISSUE TITLE
questions about bibliography format and bib file importing behavior

### ISSUE THREAD

**Issue by fishjojo** [mcmtroffaes/sphinxcontrib-bibtex#326]
Dear developers,

The bibliography generated with the default setting looks like 
```
[1] (1,2,3)
Name, tile, year, ...
```
But I wanted it to look like
```
[1] Name, title, year, ...
```
How can I achieve this?

In addition, when I use version 1.0, I don't need to configure the `bibtex_bibfiles` key and all the bib files can be found with relative paths, e.g.,
```
.. bibliography:: ../test.bib
```
But now when I use version 2.5, this doesn't work and I need to explicitly configure the `bibtex_bibfiles` key. Is there any way to restore the old behavior, because I have many text files and they are in different directories, and it is better to put the corresponding bib files in the respective directories.

Thank you for your help.

**Comment by mcmtroffaes** [comment]
For the 1st question: are these extra numbers are back-references? If so, I can't think of an easy way to get rid of these since this is handled at low-level docutils level, and built in as part of the label generation, so there's currently no way to generate a label without also having back-references. However, interestingly, docutils will not generate back-references across different documents (because docutils does not support this). So to get rid of back-references, you could put your bibliography directive in a document separate from the citations. Your other option is to use bullet or enumerated lists: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#bullet-lists-and-enumerated-lists But then labels (and references to those labels) will be missing, and this may not be what you want.

For the 2nd question: to support parallel processing, the extension needs to process all bibliography files in advance. This is an intentional design change. I recommend maintaining a single bibliography that you use across all files. I understand this can be quite annoying if you've been doing things differently before.

Does this help?

**Comment by fishjojo** [comment]
@mcmtroffaes Thanks for your explanation. I helps a lot.
