### ISSUE TITLE
conference does not sees to work

### ISSUE THREAD

**Issue by skoudoro** [mcmtroffaes/sphinxcontrib-bibtex#328]
Hi sphinxcontrib-bibtex team,

I get this error:

```
for event 'env-updated' threw an exception (exception: 'Style' object has no attribute 'format_conference')
```
 with the following:

```
@conference{corouge2004towards,
  author         = {Corouge, I. and Gouttard, S. and Gerig, G.},
  booktitle      = {International Symposium on Biomedical Imaging},
  organization   = {Citeseer},
  pages          = {344--347},
  title          = {{Towards a shape model of white matter fiber bundles
                   using diffusion tensor MRI}},
  year           = 2004
}
```

is the keyword `conference not handled? is there a workaround? 

Thanks

**Comment by mcmtroffaes** [comment]
Well, pybtex handles bibtex parsing so this is really an issue with pybtex. I suspect the default style in pybtex does not support ``@conference`` because it's not an official bibtex entry. You can use ``@inproceedings`` instead, or alternatively create a style that has a ``format_conference`` function to format it how you want.

**Comment by skoudoro** [comment]
ok Thank you for your valuable feedback

closing
