### ISSUE TITLE
Create `citation_reference` nodes programatically

### ISSUE THREAD

**Issue by lmmentel** [mcmtroffaes/sphinxcontrib-bibtex#353]
Hey :wave: 

Thanks for the awesome package, I'm a long time user :slightly_smiling_face: 

Recently I've been trying to generate doc tables from pandas dataframes to table nodes and I'm mostly there. One of the columns in the table contains citation keys and I would like them to render as links to the bibliography but since I'm not an expert in sphinx internals I'm having a hard time making it work.

What I've done so far is to create the `citation_reference` nodes in the proper cell like this:
```python
...
            if column_name == citation_column:
                paragraph = nodes.paragraph()
                if cell_value is None:
                    paragraph += nodes.Text("")
                else:
                    paragraph += nodes.citation_reference(text=str(cell_value))
...
```

which renderes the citations keys literally in square brackets, but is not resolving references correctly and gives:
```bash
...
newdata.rst:16: WARNING: citation not found: haynes2014crc [ref.ref]
...
```

I had a look at [CiteRole](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/ba6989da73a3e1bcbeba83b6c164addc487ecd21/src/sphinxcontrib/bibtex/roles.py#L32) from sphinxcontrib-bibtex but wasn't able to figure out if that's the way to proceed.

Any chance I'm missing something obvious here and could get a pointer in the right direction? 

In case it's useful here's a [draft PR](https://github.com/lmmentel/mendeleev/pull/211/files) from my project where I'm trying to get it working.

**Comment by mcmtroffaes** [comment]
Excellent question. The CiteRole will create a pending_xref, which will then get processed by the resolve_xref method of the cite domain: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/src/sphinxcontrib/bibtex/domain.py#L398

The actual nodes being generated can be found in the render method of the SphinxReferenceText class: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/ba6989da73a3e1bcbeba83b6c164addc487ecd21/src/sphinxcontrib/bibtex/style/template.py#L150

The way these are rendered depends on the target:
* by default, it will generate reference nodes directly, formatted appropriately as per style requirements
* the rinoh target will generate a citation_reference node (which then gets turned into a reference node later by sphinx)
* the latex node will produce a custom raw latex hyperlink to ensure the reference is correct (because sphinx can't do it correctly)

This all said, I think it should be fine though to generate citation_reference nodes directly, if you have all the information already at hand. You can find some sample code here:

https://github.com/mcmtroffaes/pybtex-docutils/blob/develop/src/pybtex_docutils/__init__.py#L127

... and there's a "docutils" version of sphinxcontrib-bibtex that lives there as well:

https://github.com/mcmtroffaes/pybtex-docutils/blob/develop/src/pybtex_docutils/__init__.py#L185

This is documented here:

https://github.com/mcmtroffaes/pybtex-docutils?tab=readme-ov-file#minimal-example

I think the pybtex_docutils code is likely going to be most useful for you, since it's simple and straightforward, without needing to go through all the baggage that comes with sphinx. Good luck!!!

**Comment by lmmentel** [comment]
Thanks a lot for the elaborate answer. To be honest it goes a little bit over my head.

My current thinking was to write a "simple" sphinx extension that provides a single directive to insert a table node. I was hoping that there's a node similar to e.g. `nodes.citation_reference` that I can pass my citation key (or keys) and it'll take care of the rest.

I cannot quite see how to pass that key when instantiating `SphinxReferenceText`. I saw that there's [SphinxReferenceInfo](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/ba6989da73a3e1bcbeba83b6c164addc487ecd21/src/sphinxcontrib/bibtex/style/template.py#L136) but it expects a few other args and I'm not sure how the two interface. 

I tried sth like this to create the node

```python
from sphinxcontrib.bibtex.style.template import SphinxReferenceInfo, SphinxReferenceText

info = SphinxReferenceInfo(
    builder="docutils",
    fromdocname="",
    todocname="",
    citation_id="haynes",
    title="test",
    pre_text="",
    post_text=""
)
node = SphinxReferenceText(info)
```
and it creates the instance but I'm not certain that all the empty/random strings are the way to go here. Should I be getting those arg values fro somewhere else, sphinx app instance maybe?

Is there something I'm missing here?

**Comment by mcmtroffaes** [comment]
If you want something simple, ignore SphinxReferenceText, and just look at the citation and citation_reference functions in https://github.com/mcmtroffaes/pybtex-docutils/blob/develop/src/pybtex_docutils/__init__.py - this is mostly self-contained. Both functions take a "formatted entry" but you can just feed it the data yourself. For a citation reference that is:

```
refname = docutils.nodes.fully_normalize_name(<reference_key>)
refnode = docutils.nodes.citation_reference("[%s]_" % label, refname=refname)
refnode += docutils.nodes.Text(label)
document.note_citation_ref(refnode)
```

In particular you need to note the citation ref, otherwise they won't get resolved. For setting up the citations themselves (i.e. the citation nodes), it's a little more complicated but the same principles work. Obviously the refnames need to match for the links to work correctly between citation and citation reference. Also they may need to be in the same document (or at least I encourage you to test that first, since docutils isn't designed from the ground up for cross-referencing between documents).

Does this help you further?

**Comment by lmmentel** [comment]
I think I'm back in the same point where the reference nodes are created but the references are not resolved :/

I tried to follow your example but I don't have the `label` defined, I guess this is known after the references are resolved.

This is what I tried instead:
```python
                    paragraph = nodes.paragraph()
                    if cell_value is None:
                        paragraph += nodes.Text("")
                    else:
                        refname = nodes.fully_normalize_name(cell_value)
                        refnode = nodes.citation_reference(refname=refname)
                        refnode += nodes.Text(f"{cell_value}")
                        paragraph += refnode
                        self.state.document.note_citation_ref(refnode)
```

where `self` comes from extending the class `sphinx.util.docutils,SphinxDirective`. 

When I run the build, I get the citation keys rendered inside square brackets (not links) and lots of warnings references are not resolved. The citation key are correct since I have the original page that uses the keys though ```:cite:`citation_key``` the they resolve OK.

**Comment by lmmentel** [comment]
Just to make it clear a have a separate page that I render from `.rst` source into
![image](https://github.com/user-attachments/assets/ab880524-f703-48ed-b1e3-cdd3abdcc5b9)

with the source rst looking like this:
```rst
+-------------------------+----------------------------------+----------------+--------------+------------------------------------------------------+
| Attribute name          | Description                      | Unit           | Value origin | Citation keys                                        |
+=========================+==================================+================+==============+======================================================+
| ``abundance_crust``     | Abundance in the Earth's crust   | mg/kg          | stored       | :cite:`haynes2014crc`                                |
+-------------------------+----------------------------------+----------------+--------------+------------------------------------------------------+
| ``abundance_sea``       | Abundance in the seas            | mg/L           | stored       | :cite:`haynes2014crc`                                |
+-------------------------+----------------------------------+----------------+--------------+------------------------------------------------------+
| ``atomic_number``       | Atomic number                    |                | stored       |                                                      |
+-------------------------+----------------------------------+----------------+--------------+------------------------------------------------------+
| ``atomic_radius_rahm``  | Atomic radius by Rahm et al.     | pm             | stored       | :cite:`Rahm2016,Rahm2017`                            |
+-------------------------+----------------------------------+----------------+--------------+------------------------------------------------------+
| ``atomic_radius``       | Atomic radius                    | pm             | stored       | :cite:`Slater1964`                                   |
+-------------------------+----------------------------------+----------------+--------------+------------------------------------------------------+
```

When I try to render the same table by composing a `[table]` from a sphinx extension I currently get this:
![image](https://github.com/user-attachments/assets/9950d256-cb7c-4654-8466-2d02905935c3)

Which is close but references are not resolved. Both pages are build at the same time so there is no issue with keys etc.

**Comment by mcmtroffaes** [comment]
Hmmm... How are you generating the citations themselves? The code should be something like this:

```
name = docutils.nodes.fully_normalize_name(<reference_key>)
citation = docutils.nodes.citation()
citation["names"].append(name)
citation += docutils.nodes.label("", label)
citation += docutils.nodes.paragraph(...)
document.note_citation(citation)
document.note_explicit_target(citation, citation)
```

**Comment by lmmentel** [comment]
Do I need to create `citation` nodes along the `citation_reference` nodes even those same references are use elsewhere in the build?

Here's the current code I tried:

```python
                    paragraph = nodes.paragraph()
                    if cell_value is None:
                        paragraph += nodes.Text("")
                    else:
                        refname = nodes.fully_normalize_name(cell_value)
                        
                        #add citation
                        citation = nodes.citation()
                        citation["names"].append(refname)
                        citation += nodes.label("", refname)
                        citation += nodes.paragraph(text=str(cell_value))
                        self.state.document.note_citation(citation)
                        self.state.document.note_explicit_target(citation, citation)
                        
                        # add citation reference
                        refnode = nodes.citation_reference(refname=refname)
                        refnode += nodes.Text(f"{cell_value}")
                        self.state.document.note_citation_ref(refnode)
                        paragraph += refnode
```

Not sure the order is right but I tried reference before citation and it didn't help. At this point I'm mostly doing trial and error since this stuff is not easy to figure out. 

I'm getting, warnings like:
```bash
/newdata.rst:4: WARNING: Duplicate explicit target name: "haynes2014crc". [docutils]
/newdata.rst:4: WARNING: Duplicate explicit target name: "meija2016,iupac-weights". [docutils]
...
```
and
```bash
/newdata.rst:16: WARNING: citation not found: haynes2014crc [ref.ref]
/newdata.rst:16: WARNING: citation not found: haynes2014crc [ref.ref]
/newdata.rst:16: WARNING: citation not found: Slater1964 [ref.ref]
...
```

I'm starting to think that it might be easier to convert the dataframe into `.rst` and just insert that into source file then run sphinx build on that instead of fiddling with building the table node by node.

Appreciate if you have any further suggestions.

**Comment by mcmtroffaes** [comment]
Each node is a piece of text, so typically you'll have all your citation nodes in one place (e.g. at the end of the document), whilst citation_reference nodes are wherever you need a citation. I suggest you try to make it work without relying on sphinxcontrib-bibtex... (and only on pybtex_docutils, or code copied from it).

Sorry to hear this turns out to be such a headache, and that I can't be more helpful...

**Comment by lmmentel** [comment]
No worries. Thanks a lot for all your suggestions and help on this. I guess I was a bit too optimistic when planning this out.

**Comment by mcmtroffaes** [comment]
Ok. I'll close this then.
