### ISSUE TITLE
Capitalisation in paper names

### ISSUE THREAD

**Issue by TamaraAtanasoska** [mcmtroffaes/sphinxcontrib-bibtex#354]
HI! We use `sphinxcontrib-bibtex` in `fairlearn`. I noticed that the names of the papers are always lowercase, even if they have the first letter uppercase style like [in this case](https://github.com/fairlearn/fairlearn/blob/main/docs/refs.bib#L81), [which renders to this](https://fairlearn.org/v0.12/user_guide/further_resources.html#papers). 

I wanted to ask if this is a deliberate design choice, and why? Maybe an option can be added in the config for capitalisation preferences? Happy to attempt to help with this.

**Comment by mcmtroffaes** [comment]
I cannot answer your question about design choice, since sphinxcontrib-bibtex does not format the citations. This is handled by pybtex (which sphinxcontrib-bibtex uses for formatting). There is some documentation on how to change pybtex styles here:

https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-formatting-sorting-and-labelling

You then can achieve your desired capitalisation behaviour by overriding the appropriate methods of your style class.

Does this give enough of a pointer to help you further?

**Comment by TamaraAtanasoska** [comment]
I see, thank you! I was wondering why that is the case, but I suppose it is a compromise between all the different citation styles, and as the docs say it is individually customisable. I will overwrite the style then :)
